name = "cloudtms"
main = "broker/src/index.js"
compatibility_date = "2025-10-13"

[vars]
SUPABASE_URL = "https://zojgukxyyklcyjbyyqlz.supabase.co"
ALLOWED_ORIGINS = "https://cloudtms.arthur-rai.co.uk,https://kierarthur.github.io"
COOKIE_SAME_SITE = "None"
PRESIGN_EXPIRES_SECONDS = "600"
UPLOAD_MAX_BYTES = "300000"
BREAK_EXPECTED_MINUTES = "60"
UK_TZ_SKEW_MS = "180000"
TSFIN_MAX_BATCHES = "10"
TSFIN_BATCH_SIZE = "50"

# === Email / Outbox broker ===
POWER_AUTOMATE_EMAIL_WEBHOOK_URL = "https://defaultba10833977be4042a72b025b785d1f.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/26270a54fbb941ad80f4f1efcc2ce016/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=JHeTB1I-IBZY04eprseJR8L1O6O5nGqFE6UWAbufLbU"
EMAIL_DRAIN_LIMIT_DEFAULT = "10"
EMAIL_MAX_PAYLOAD_BYTES = "18874368"
PUBLIC_DOWNLOAD_BASE_URL = "https://cloudtms.arthur-rai.co.uk/api/files/download"

[[r2_buckets]]
binding = "R2"
bucket_name = "timesheets-signatures"

[[kv_namespaces]]
binding = "SESSIONS"
id = "3102e18c46b841d2b55918c1ae054491"
preview_id = "6b8fb70351db4cac91583a9cc6c2074b"

[triggers]
crons = ["*/5 * * * *"]

[browser]
binding = "BROWSER"

