name = "cloudtms"
main = "broker/src/index.js"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]

[vars]
SUPABASE_URL = "https://zojgukxyyklcyjbyyqlz.supabase.co"
ALLOWED_ORIGINS = "https://cloudtms.arthur-rai.co.uk,https://kierarthur.github.io"
COOKIE_SAME_SITE = "None"
PRESIGN_EXPIRES_SECONDS = "600"
UPLOAD_MAX_BYTES = "300000"
BREAK_EXPECTED_MINUTES = "60"
UK_TZ_SKEW_MS = "180000"
TSFIN_MAX_BATCHES = "10"
TSFIN_BATCH_SIZE = "50"

# === Email / Outbox broker ===
EMAIL_DRAIN_LIMIT_DEFAULT = "10"
EMAIL_MAX_PAYLOAD_BYTES = "18874368"
PUBLIC_DOWNLOAD_BASE_URL = "https://cloudtms.arthur-rai.co.uk/api/files/download"

# === Invoicing stationery ===
INVOICE_STATIONERY_BUCKET = "timesheets-signatures"
# Use the PNG you uploaded (A4, full-bleed). Keep exact path/casing.
INVOICE_STATIONERY_KEY = "Assets/Stationery/Letterhead/A4/Letterhead_v1@300dpi.png"

# New for TS rendering
TIMESHEET_TEMPLATE_KEY = "Assets/Stationery/Timesheet/Blank Timesheet.pdf"

[[r2_buckets]]
binding = "R2"
bucket_name = "timesheets-signatures"

[[kv_namespaces]]
binding = "SESSIONS"
id = "3102e18c46b841d2b55918c1ae054491"
preview_id = "6b8fb70351db4cac91583a9cc6c2074b"

# Enable Workers Browser Rendering
[browser]
binding = "BROWSER"

[triggers]
crons = ["*/5 * * * *"]  # every 5 minutes

# =========================
# Workers Logs (Observability)
# =========================
# Dev/preview: log EVERYTHING with CF's invocation logs
[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1     # 100% while debugging

# Production: still on, but sample to reduce noise; bump to 1.0 when chasing a bug
[env.production.observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 0.25  # 25% to start; adjust as needed
