-- CANDIDATE release file generated by Worker AF (H8) from the tested Stage 2 combined candidate.
-- NOT committed, NOT installed anywhere. Source pieces and hashes: h8/RELEASE_FORM_RESULT.json.
-- Probe/prototype identifiers renamed to production names per h8/tools/rename_map.json.
-- Policy X: no economic-key derivation, freshness or post-Draft behaviour change beyond the tested winners.
-- Repeatable CloudTMS privilege authority: banking_pay_stage2_grants_v1 (GENERATED from h0/WINNER_REPLACEMENTS_A25_GRANTS.sql as regenerated by Worker AT, re-regenerated for A33 by Worker AX and for A34 by Worker BV: h8/release_a34/regenerated/WINNER_REPLACEMENTS_A25_GRANTS.regenerated_a34.sql, sha256 cea54051c5731f083794f57d1145c1971bf50e2ef3bce6b1082377b0d7e4aecb).
-- Do not hand-edit: regenerate A25 (h8/release_a34/tools/a34_generate_grants.py) after any new function, then rebuild.
-- Installs LAST (latest timestamp), so the release finishes in this approved ACL state on NEW and UPGRADE.

\set ON_ERROR_STOP on

begin;
-- A25 WINNER REPLACEMENT, REGENERATED by Worker AT (H8 release-proof, 26 Sep 2026) from Worker AE's A25
-- (sha256 ea2efb3009e8d19a...) so that it also covers A26, A27, A28, A29, A30 and A24 v2. Original author: Worker AE "grants": exact privilege closure for every function,
-- trigger function, table and schema that the combined Stage 2 candidate (A2-A30 + TESTED_STATE_EXTRACT)
-- adds or changes. Privilege statements ONLY: no function body, signature, owner, volatility, search_path,
-- table, column, index, trigger, row, money, Policy X or settings change.
-- RE-REGENERATED by Worker AX (release-a33, 26 Sep 2026) with h8/release_a33/tools/a33_generate_grants.py so
-- that it also reasserts both A33 overloads of public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1
-- (section 6 and the section 7 service_only self-check). No other privilege statement changes.
-- RE-REGENERATED by Worker BV (release-a34, 27 Sep 2026) with h8/release_a34/tools/a34_generate_grants.py so
-- that it also covers A34 (h0/WINNER_REPLACEMENTS_A34_LEGACY_CASE_BLOCKER.sql): three new private routines
-- (section 3, owner only) and public.pay_workbench_draft_certificate_constituent_ref_page_v8 (section 6,
-- service_role only). A34's other five routines were already covered. No other privilege statement changes.
--
-- Why this file is needed (see workers/grants/GRANTS_REPORT.md):
--   * CREATE OR REPLACE keeps an existing function's ACL, but a NEW function receives PostgreSQL's built-in
--     default (EXECUTE to PUBLIC). The repository's owner default privileges are per-schema for `public`
--     only, and a per-schema `revoke ... from PUBLIC` cannot remove the built-in global PUBLIC EXECUTE
--     (proved in a rolled-back transaction: a new public function still gets `=X`, a new private function
--     gets `=X`). So every new candidate function reaches the release target executable by PUBLIC, i.e. by
--     anon, authenticated and service_role, unless its own file revokes it.
--   * 42 of the original 45 new functions carry no REVOKE (only A10, A17 and A24 revoke, one function each;
--     A30 adds one more new function and revokes it itself). The `private` schema's
--     USAGE (granted to service_role, withheld from anon/authenticated) is the only thing standing between
--     those SECURITY DEFINER helpers and the browser roles, and it does not protect them from service_role.
--   * Changed functions keep the release target's ACL, which already matches the repository contract;
--     they are reasserted here so this closure finishes in its own approved state on NEW and UPGRADE
--     replays regardless of file order (AGENTS.md: a changed closure must end in its approved ACL state).
--
-- Conventions applied:
--   private.*                          -> owner only (revoked from PUBLIC, anon, authenticated, service_role).
--                                        Every caller of each new private helper is SECURITY DEFINER owned by
--                                        the same owner, or the helper is a trigger function (trigger firing
--                                        does not check EXECUTE), so no role needs EXECUTE.
--   public changed RPCs                -> service_role only (the repository contract ACL for every one).
--   public._pay_batch_draft_stale_hint_on_view_v1 (new, A10/A24)
--                                      -> owner only: its sole caller is public.pay_batch_get (SECURITY
--                                        DEFINER). Precedent: public.tsfin_weekly_source_hours_v1.
--   (prototype evidence schema, now private.bpay_protected_reference_*) (prototype schema, tables, functions)
--                                      -> owner only. Prototype names must be renamed before release and this
--                                        section re-targeted at the final names (release blocker, not a grant).
--   search_path                        -> every SECURITY DEFINER function added or changed already pins
--                                        search_path, so no ALTER FUNCTION ... SET search_path is required.
--
-- The release engine maps the logical owner `postgres` to CURRENT_USER; this file names no owner.
-- No BEGIN/COMMIT here on purpose: the owning release closure supplies the transaction (and this file is
-- proved only inside an outer BEGIN ... ROLLBACK). LOCAL candidate only; release as a new timestamped
-- repeatable through the protected database-release workflow, AFTER every A-file it covers.


-- ---------------------------------------------------------------------------------------------------
-- 1. Prototype schema (prototype evidence schema, now private.bpay_protected_reference_*) (TESTED_STATE_EXTRACT): schema, tables and functions.
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON TABLE private.bpay_protected_reference_events_v1 FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.bpay_protected_reference_heads_v1 FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_authorisation_signature_v1(uuid,uuid,text,integer,integer,text,text[],smallint,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_capture_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_genesis_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_page_v1(uuid,bigint,bigint,integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_for_root_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_valid_v1(jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_reference_try_family_gate_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- 2. New private tables (TESTED_STATE_EXTRACT clock prototype).
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON TABLE private.bpay_clock_families_v1 FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE private.bpay_clock_rows_v1 FROM PUBLIC, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- 3. New private functions (40; A17, A24, A30 and A34 ones are reasserted).
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON FUNCTION private._candidate_expense_source_family_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private._candidate_expense_source_root_guard_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_authorisation_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_clock_changed_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_clock_override_changed_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_clock_rebuild_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_clock_retire_family_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_clock_retirement_changed_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_entitlement_financial_scope_v1(uuid[]) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_expense_classification_lineage_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_expense_classification_ts_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_expense_classification_week_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_expense_identity_gate_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_finance_component_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_has_uncleared_advance_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_item_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_lineage_work_binding_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_family_for_current_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_protected_root_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_family_current_gate_v1(text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_row_gate_v1(uuid,boolean) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_row_wait_gate_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_settled_financial_scope_v1(uuid[]) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_auth_family_gate_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_authorise_identity_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_authorise_lock_v1(uuid,uuid,uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_family_try_lock_v1(text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_lineage_family_gate_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_protected_family_gate_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_source_timesheet_family_gate_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_timesheet_pay_state_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_timesheet_payment_overrides_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_timesheet_work_revision_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.bpay_ts_pay_adjustments_work_reference_v1() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_batch_source_head_drift_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_batch_v8_draft_preparation_unfinished_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_recovery_type_capped_allocate_v1(uuid,date,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.s3p_recovery_age_key_v1(text,timestamp with time zone,timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.s3p_recovery_order_key_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_entitlement_head_ledger_mark_v1() FROM PUBLIC, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- 4. New public helper (A10, replaced by A24): owner only.
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public._pay_batch_draft_stale_hint_on_view_v1(uuid,integer,integer) FROM PUBLIC, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- 5. Changed private functions (18; candidate replacements incl. A26-A30): reassert the contract's owner-only ACL.
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON FUNCTION private._candidate_expense_components_sync_financial_v1(uuid,timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private._candidate_expense_summary_queue_v1(uuid,timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private._timesheet_duplicate_expense_review_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_sync_overpayments_from_workbench_workspace_v1(uuid,uuid,uuid,uuid,date,date,uuid,text,uuid[],jsonb,uuid,uuid[],uuid[]) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_candidate_bounded_scope_v1(uuid,uuid,jsonb,integer,uuid[],uuid[],uuid[],uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_candidate_source_build_chunk_legacy_v1(uuid,uuid,jsonb,jsonb,integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_modal_blocked_presentation_v2(jsonb,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_modal_source_issue_members_v2(banking_pay_workbench_sessions,text,jsonb,boolean) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_recovery_selection_overlay_apply_v1(uuid,uuid,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_settled_certificate_constituent_seed_v8(uuid,integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_settled_certificate_preview_contract_v8(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.pay_workbench_unit_economic_occurrence_page_v1(uuid,text,text,uuid,text,integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_entitlement_publish_core_v1(jsonb,text,jsonb,uuid,text,uuid,jsonb,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_first_authorisation_context_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_first_authorise_core_v1(uuid,text,uuid,jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_ordinary_authorisation_guard_v1(uuid,text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_workbench_inventory_seed_page_v1(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.weekly_source_workbench_inventory_track_v1() FROM PUBLIC, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- 6. Changed public functions (36; candidate replacements incl. A23, A26-A30, A33 and A34): reassert the
--    repository contract ACL (service_role only). Three are members of the frozen Candidate-named SECURITY DEFINER
--    manifest (pay_preview_candidate_collect_scope, _pay_workbench_candidate_serial_active_state,
--    pay_workbench_mark_candidate_dirty); the reasserted tuple (service_role yes, anon no, authenticated no) is
--    exactly the sealed one, so that manifest's count/hash does not move.
-- ---------------------------------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public._pay_active_settled_components(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_active_settled_components(uuid[]) TO service_role;
REVOKE ALL ON FUNCTION public._pay_batch_item_economic_components(uuid,uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_batch_item_economic_components(uuid,uuid[]) TO service_role;
REVOKE ALL ON FUNCTION public._pay_current_timesheet_entitlement_components(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_current_timesheet_entitlement_components(uuid[]) TO service_role;
REVOKE ALL ON FUNCTION public._pay_outstanding_components(uuid[],uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_outstanding_components(uuid[],uuid) TO service_role;
REVOKE ALL ON FUNCTION public._pay_reserved_components(uuid[],uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_reserved_components(uuid[],uuid) TO service_role;
REVOKE ALL ON FUNCTION public._pay_workbench_candidate_serial_active_state(uuid,uuid,text,jsonb,timestamp with time zone) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._pay_workbench_candidate_serial_active_state(uuid,uuid,text,jsonb,timestamp with time zone) TO service_role;
REVOKE ALL ON FUNCTION public.pay_bank_csv_export_summary_get(uuid,text,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_bank_csv_export_summary_get(uuid,text,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_export_csv_rows(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_export_csv_rows(uuid,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_freshness_result_get(uuid,uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_freshness_result_get(uuid,uuid,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_get(uuid,uuid,text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_get(uuid,uuid,text,integer) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_get_section_page(uuid,text,jsonb,integer,uuid,jsonb,jsonb,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_get_section_page(uuid,text,jsonb,integer,uuid,jsonb,jsonb,text) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_validate_freshness(uuid,uuid,boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_validate_freshness(uuid,uuid,boolean) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batch_validate_freshness_chunk(uuid,jsonb,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batch_validate_freshness_chunk(uuid,jsonb,integer) TO service_role;
REVOKE ALL ON FUNCTION public.pay_batches_list(integer,integer,text,uuid,text,boolean,boolean,boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_batches_list(integer,integer,text,uuid,text,boolean,boolean,boolean) TO service_role;
REVOKE ALL ON FUNCTION public.pay_export_bank_csv(uuid,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_export_bank_csv(uuid,text) TO service_role;
REVOKE ALL ON FUNCTION public.pay_finance_components_sync_from_preview(uuid,jsonb,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_finance_components_sync_from_preview(uuid,jsonb,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_preview_candidate_build_canonical_lines(jsonb,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_preview_candidate_build_canonical_lines(jsonb,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_preview_candidate_build_finance_case_baseline(jsonb,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_preview_candidate_build_finance_case_baseline(jsonb,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_preview_candidate_collect_scope(jsonb,uuid,jsonb,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_preview_candidate_collect_scope(jsonb,uuid,jsonb,integer) TO service_role;
REVOKE ALL ON FUNCTION public.pay_search(text,integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_search(text,integer,integer) TO service_role;
REVOKE ALL ON FUNCTION public.pay_timesheet_summary_advance_state_refresh(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_timesheet_summary_advance_state_refresh(uuid,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_complete_job(uuid,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_complete_job(uuid,jsonb) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_contract_client_dirty_fanout_chunk(uuid,jsonb,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_contract_client_dirty_fanout_chunk(uuid,jsonb,integer) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_dirty_event_enqueue(text,text,text,uuid,uuid[],uuid[],jsonb,text,integer,timestamp with time zone) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_dirty_event_enqueue(text,text,text,uuid,uuid[],uuid[],jsonb,text,integer,timestamp with time zone) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_draft_certificate_constituent_ref_page_v8(uuid,integer,integer,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_draft_certificate_constituent_ref_page_v8(uuid,integer,integer,text) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_mark_candidate_dirty() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_mark_candidate_dirty() TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_reconcile_successful_source_build(uuid,uuid,uuid,bigint,bigint,uuid,text,jsonb,jsonb,boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_reconcile_successful_source_build(uuid,uuid,uuid,bigint,bigint,uuid,text,jsonb,jsonb,boolean) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid,jsonb) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_scope_blocker_state_v1(uuid,bigint,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_scope_blocker_state_v1(uuid,bigint,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_scope_change_tx_token_v1() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_scope_change_tx_token_v1() TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_scope_reconcile_drain_one_v1(integer,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_scope_reconcile_drain_one_v1(integer,text) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_settled_certificate_build_start_v8(uuid,uuid,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_settled_certificate_build_start_v8(uuid,uuid,text) TO service_role;
REVOKE ALL ON FUNCTION public.pay_workbench_source_build_attempt_claim_start_v1(text,text,integer,timestamp with time zone,uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pay_workbench_source_build_attempt_claim_start_v1(text,text,integer,timestamp with time zone,uuid,uuid) TO service_role;
REVOKE ALL ON FUNCTION public.timesheet_authorise_generic_atomic(uuid,uuid,uuid,timestamp with time zone,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.timesheet_authorise_generic_atomic(uuid,uuid,uuid,timestamp with time zone,text) TO service_role;
REVOKE ALL ON FUNCTION public.weekly_source_first_authorise_v1(uuid,uuid,text,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.weekly_source_first_authorise_v1(uuid,uuid,text,uuid) TO service_role;

-- ---------------------------------------------------------------------------------------------------
-- 7. Fail-closed verification of this closure (catalogue only; reads no application rows).
-- ---------------------------------------------------------------------------------------------------
DO $a25_verify$
DECLARE
  v_bad text;
BEGIN
  WITH owner_only(sig) AS (VALUES
    ('private.bpay_protected_reference_authorisation_signature_v1(uuid,uuid,text,integer,integer,text,text[],smallint,jsonb)'),
    ('private.bpay_protected_reference_capture_v1()'),
    ('private.bpay_protected_reference_genesis_v1(uuid)'),
    ('private.bpay_protected_reference_page_v1(uuid,bigint,bigint,integer)'),
    ('private.bpay_protected_reference_v1(uuid)'),
    ('private.bpay_protected_reference_for_root_v1(uuid)'),
    ('private.bpay_protected_reference_valid_v1(jsonb)'),
    ('private.bpay_protected_reference_try_family_gate_v1(uuid)'),
    ('private._candidate_expense_source_family_v1(uuid)'),
    ('private._candidate_expense_source_root_guard_v1()'),
    ('private.bpay_authorisation_work_reference_v1()'),
    ('private.bpay_clock_changed_v1()'),
    ('private.bpay_clock_override_changed_v1()'),
    ('private.bpay_clock_rebuild_v1(uuid)'),
    ('private.bpay_clock_retire_family_v1(uuid)'),
    ('private.bpay_clock_retirement_changed_v1()'),
    ('private.bpay_entitlement_financial_scope_v1(uuid[])'),
    ('private.bpay_expense_classification_lineage_v1()'),
    ('private.bpay_expense_classification_ts_v1()'),
    ('private.bpay_expense_classification_week_v1()'),
    ('private.bpay_expense_identity_gate_v1(uuid)'),
    ('private.bpay_finance_component_work_reference_v1()'),
    ('private.bpay_has_uncleared_advance_v1(uuid)'),
    ('private.bpay_item_work_reference_v1()'),
    ('private.bpay_lineage_work_binding_v1()'),
    ('private.bpay_protected_family_for_current_v1(uuid)'),
    ('private.bpay_protected_root_reference_v1()'),
    ('private.bpay_source_family_current_gate_v1(text)'),
    ('private.bpay_source_row_gate_v1(uuid,boolean)'),
    ('private.bpay_source_row_wait_gate_v1(uuid)'),
    ('private.bpay_settled_financial_scope_v1(uuid[])'),
    ('private.bpay_source_auth_family_gate_v1()'),
    ('private.bpay_source_authorise_identity_v1(uuid)'),
    ('private.bpay_source_authorise_lock_v1(uuid,uuid,uuid)'),
    ('private.bpay_source_family_try_lock_v1(text)'),
    ('private.bpay_source_lineage_family_gate_v1()'),
    ('private.bpay_source_protected_family_gate_v1()'),
    ('private.bpay_source_timesheet_family_gate_v1()'),
    ('private.bpay_timesheet_pay_state_work_reference_v1()'),
    ('private.bpay_timesheet_payment_overrides_work_reference_v1()'),
    ('private.bpay_timesheet_work_revision_v1()'),
    ('private.bpay_ts_pay_adjustments_work_reference_v1()'),
    ('private.pay_batch_source_head_drift_v1(uuid)'),
    ('private.pay_batch_v8_draft_preparation_unfinished_v1(uuid)'),
    ('private.pay_workbench_recovery_type_capped_allocate_v1(uuid,date,jsonb)'),
    ('private.s3p_recovery_age_key_v1(text,timestamp with time zone,timestamp with time zone)'),
    ('private.s3p_recovery_order_key_v1(uuid)'),
    ('private.weekly_source_entitlement_head_ledger_mark_v1()'),
    ('public._pay_batch_draft_stale_hint_on_view_v1(uuid,integer,integer)'),
    ('private._candidate_expense_components_sync_financial_v1(uuid,timestamp with time zone)'),
    ('private._candidate_expense_summary_queue_v1(uuid,timestamp with time zone)'),
    ('private._timesheet_duplicate_expense_review_v1(uuid)'),
    ('private.pay_sync_overpayments_from_workbench_workspace_v1(uuid,uuid,uuid,uuid,date,date,uuid,text,uuid[],jsonb,uuid,uuid[],uuid[])'),
    ('private.pay_workbench_candidate_bounded_scope_v1(uuid,uuid,jsonb,integer,uuid[],uuid[],uuid[],uuid)'),
    ('private.pay_workbench_candidate_source_build_chunk_legacy_v1(uuid,uuid,jsonb,jsonb,integer)'),
    ('private.pay_workbench_modal_blocked_presentation_v2(jsonb,jsonb)'),
    ('private.pay_workbench_modal_source_issue_members_v2(banking_pay_workbench_sessions,text,jsonb,boolean)'),
    ('private.pay_workbench_recovery_selection_overlay_apply_v1(uuid,uuid,jsonb)'),
    ('private.pay_workbench_settled_certificate_constituent_seed_v8(uuid,integer)'),
    ('private.pay_workbench_settled_certificate_preview_contract_v8(uuid)'),
    ('private.pay_workbench_unit_economic_occurrence_page_v1(uuid,text,text,uuid,text,integer)'),
    ('private.weekly_source_entitlement_publish_core_v1(jsonb,text,jsonb,uuid,text,uuid,jsonb,jsonb)'),
    ('private.weekly_source_first_authorisation_context_v1(uuid)'),
    ('private.weekly_source_first_authorise_core_v1(uuid,text,uuid,jsonb)'),
    ('private.weekly_source_ordinary_authorisation_guard_v1(uuid,text)'),
    ('private.weekly_source_workbench_inventory_seed_page_v1(uuid)'),
    ('private.weekly_source_workbench_inventory_track_v1()')
  ), service_only(sig) AS (VALUES
    ('public._pay_active_settled_components(uuid[])'),
    ('public._pay_batch_item_economic_components(uuid,uuid[])'),
    ('public._pay_current_timesheet_entitlement_components(uuid[])'),
    ('public._pay_outstanding_components(uuid[],uuid)'),
    ('public._pay_reserved_components(uuid[],uuid)'),
    ('public._pay_workbench_candidate_serial_active_state(uuid,uuid,text,jsonb,timestamp with time zone)'),
    ('public.pay_bank_csv_export_summary_get(uuid,text,uuid)'),
    ('public.pay_batch_export_csv_rows(uuid,uuid)'),
    ('public.pay_batch_freshness_result_get(uuid,uuid,uuid)'),
    ('public.pay_batch_get(uuid,uuid,text,integer)'),
    ('public.pay_batch_get_section_page(uuid,text,jsonb,integer,uuid,jsonb,jsonb,text)'),
    ('public.pay_batch_validate_freshness(uuid,uuid,boolean)'),
    ('public.pay_batch_validate_freshness_chunk(uuid,jsonb,integer)'),
    ('public.pay_batches_list(integer,integer,text,uuid,text,boolean,boolean,boolean)'),
    ('public.pay_export_bank_csv(uuid,text)'),
    ('public.pay_finance_components_sync_from_preview(uuid,jsonb,uuid)'),
    ('public.pay_preview_candidate_build_canonical_lines(jsonb,uuid)'),
    ('public.pay_preview_candidate_build_finance_case_baseline(jsonb,uuid)'),
    ('public.pay_preview_candidate_collect_scope(jsonb,uuid,jsonb,integer)'),
    ('public.pay_search(text,integer,integer)'),
    ('public.pay_timesheet_summary_advance_state_refresh(uuid,uuid)'),
    ('public.pay_workbench_complete_job(uuid,jsonb)'),
    ('public.pay_workbench_contract_client_dirty_fanout_chunk(uuid,jsonb,integer)'),
    ('public.pay_workbench_dirty_event_enqueue(text,text,text,uuid,uuid[],uuid[],jsonb,text,integer,timestamp with time zone)'),
    ('public.pay_workbench_draft_certificate_constituent_ref_page_v8(uuid,integer,integer,text)'),
    ('public.pay_workbench_mark_candidate_dirty()'),
    ('public.pay_workbench_reconcile_successful_source_build(uuid,uuid,uuid,bigint,bigint,uuid,text,jsonb,jsonb,boolean)'),
    ('public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid)'),
    ('public.pay_workbench_revalidate_zero_retained_recovery_headroom_v1(uuid,uuid,jsonb)'),
    ('public.pay_workbench_scope_blocker_state_v1(uuid,bigint,uuid)'),
    ('public.pay_workbench_scope_change_tx_token_v1()'),
    ('public.pay_workbench_scope_reconcile_drain_one_v1(integer,text)'),
    ('public.pay_workbench_settled_certificate_build_start_v8(uuid,uuid,text)'),
    ('public.pay_workbench_source_build_attempt_claim_start_v1(text,text,integer,timestamp with time zone,uuid,uuid)'),
    ('public.timesheet_authorise_generic_atomic(uuid,uuid,uuid,timestamp with time zone,text)'),
    ('public.weekly_source_first_authorise_v1(uuid,uuid,text,uuid)')
  ), expected AS (
    SELECT sig, false AS svc FROM owner_only UNION ALL SELECT sig, true FROM service_only
  ), checked AS (
    SELECT e.sig, pg_catalog.to_regprocedure(e.sig) AS oid, e.svc FROM expected e
  )
  SELECT pg_catalog.string_agg(c.sig, ', ' ORDER BY c.sig) INTO v_bad
  FROM checked c
  LEFT JOIN pg_catalog.pg_proc p ON p.oid = c.oid
  WHERE c.oid IS NULL
     OR pg_catalog.has_function_privilege('anon', p.oid, 'EXECUTE')
     OR pg_catalog.has_function_privilege('authenticated', p.oid, 'EXECUTE')
     OR pg_catalog.has_function_privilege('service_role', p.oid, 'EXECUTE') <> c.svc
     OR EXISTS (SELECT 1 FROM pg_catalog.aclexplode(coalesce(p.proacl, pg_catalog.acldefault('f', p.proowner))) a
                WHERE a.grantee <> p.proowner
                  AND NOT (c.svc AND a.grantee = 'service_role'::pg_catalog.regrole AND a.privilege_type = 'EXECUTE'))
     OR (p.prosecdef AND NOT EXISTS (SELECT 1 FROM pg_catalog.unnest(coalesce(p.proconfig, '{}'::text[])) s
                                     WHERE s LIKE 'search\_path=%'));
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'ZX999', MESSAGE = 'A25_GRANTS_CLOSURE_FAILED', DETAIL = v_bad;
  END IF;

  SELECT pg_catalog.string_agg(c.oid::regclass::text, ', ') INTO v_bad
  FROM pg_catalog.pg_class c
  WHERE c.oid IN ('private.bpay_protected_reference_events_v1'::regclass, 'private.bpay_protected_reference_heads_v1'::regclass,
                  'private.bpay_clock_families_v1'::regclass, 'private.bpay_clock_rows_v1'::regclass)
    AND EXISTS (SELECT 1 FROM pg_catalog.aclexplode(coalesce(c.relacl, pg_catalog.acldefault('r', c.relowner))) a
                WHERE a.grantee <> c.relowner);
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'ZX999', MESSAGE = 'A25_GRANTS_TABLE_CLOSURE_FAILED', DETAIL = v_bad;
  END IF;
END
$a25_verify$;

commit;
