-- CANDIDATE release file generated by Worker AF (H8) from the tested Stage 2 combined candidate.
-- NOT committed, NOT installed anywhere. Source pieces and hashes: h8/RELEASE_FORM_RESULT.json.
-- Probe/prototype identifiers renamed to production names per h8/tools/rename_map.json.
-- Policy X: no economic-key derivation, freshness or post-Draft behaviour change beyond the tested winners.
-- Repeatable CloudTMS trigger authority: banking_pay_stage2_triggers_v1
-- Every trigger is dropped-if-exists then created, so a rerun of this closure is idempotent. Trigger names were
-- renamed without changing the relative (alphabetical) firing order on any table: h8/evidence/TRIGGER_ORDER_CHECK.json.

\set ON_ERROR_STOP on

begin;

-- private.bpay_clock_rows_v1.bpay_clock_retire_v1  (piece A1_EXTRACT; tested name bpay_clock_retire_probe)
DROP TRIGGER IF EXISTS bpay_clock_retire_v1 ON private.bpay_clock_rows_v1;
CREATE TRIGGER bpay_clock_retire_v1 AFTER DELETE OR UPDATE OF family_id ON private.bpay_clock_rows_v1 FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_retirement_changed_v1();

-- public.candidate_expense_components.candidate_expense_source_root_guard_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS candidate_expense_source_root_guard_v1 ON public.candidate_expense_components;
CREATE TRIGGER candidate_expense_source_root_guard_v1 BEFORE INSERT OR UPDATE OF owning_timesheet_id, lifecycle_state ON public.candidate_expense_components FOR EACH ROW EXECUTE FUNCTION private._candidate_expense_source_root_guard_v1();

-- public.contract_weeks.bpay_expense_classification_week_after_v1  (piece A1_EXTRACT; tested name bpay_expense_classification_week_after_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_week_after_v1 ON public.contract_weeks;
CREATE TRIGGER bpay_expense_classification_week_after_v1 AFTER INSERT OR UPDATE OF timesheet_id, contract_id, week_ending_date, additional_seq, is_adjustment ON public.contract_weeks FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_week_v1();

-- public.contract_weeks.bpay_expense_classification_week_before_v1  (piece A13; tested name bpay_expense_classification_week_before_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_week_before_v1 ON public.contract_weeks;
CREATE TRIGGER bpay_expense_classification_week_before_v1
 BEFORE INSERT OR DELETE OR UPDATE OF timesheet_id, contract_id, week_ending_date, additional_seq, is_adjustment
 ON public.contract_weeks FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_week_v1();

-- public.pay_batch_items.bpay_item_work_reference_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_item_work_reference_v1 ON public.pay_batch_items;
CREATE TRIGGER bpay_item_work_reference_v1 BEFORE INSERT OR UPDATE OF timesheet_id, frozen_source_basis_json, bpay_direct_source_timesheet_id_v1, bpay_direct_work_key_v1, bpay_direct_work_revision_v1 ON public.pay_batch_items FOR EACH ROW EXECUTE FUNCTION private.bpay_item_work_reference_v1();

-- public.pay_finance_case_components.bpay_finance_component_work_reference_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_finance_component_work_reference_v1 ON public.pay_finance_case_components;
CREATE TRIGGER bpay_finance_component_work_reference_v1 BEFORE INSERT OR UPDATE OF linked_timesheet_id, bpay_work_key_v1, bpay_work_revision_v1 ON public.pay_finance_case_components FOR EACH ROW EXECUTE FUNCTION private.bpay_finance_component_work_reference_v1();

-- public.timesheet_pay_state.bpay_work_reference_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_work_reference_v1 ON public.timesheet_pay_state;
CREATE TRIGGER bpay_work_reference_v1 BEFORE INSERT OR UPDATE OF timesheet_id, bpay_work_key_v1, bpay_work_revision_v1 ON public.timesheet_pay_state FOR EACH ROW EXECUTE FUNCTION private.bpay_timesheet_pay_state_work_reference_v1();

-- public.timesheet_payment_overrides.bpay_clock_retire_v1  (piece A1_EXTRACT; tested name bpay_clock_retire_probe)
DROP TRIGGER IF EXISTS bpay_clock_retire_v1 ON public.timesheet_payment_overrides;
CREATE TRIGGER bpay_clock_retire_v1 AFTER DELETE OR UPDATE OF bpay_clock_family_id_v1 ON public.timesheet_payment_overrides FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_retirement_changed_v1();

-- public.timesheet_payment_overrides.bpay_work_reference_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_work_reference_v1 ON public.timesheet_payment_overrides;
CREATE TRIGGER bpay_work_reference_v1 BEFORE INSERT OR UPDATE OF timesheet_id, bpay_work_key_v1, bpay_work_revision_v1 ON public.timesheet_payment_overrides FOR EACH ROW EXECUTE FUNCTION private.bpay_timesheet_payment_overrides_work_reference_v1();

-- public.timesheet_payment_overrides.bpay_z_clock_override_v1  (piece A1_EXTRACT; tested name bpay_z_clock_override_probe)
DROP TRIGGER IF EXISTS bpay_z_clock_override_v1 ON public.timesheet_payment_overrides;
CREATE TRIGGER bpay_z_clock_override_v1 BEFORE INSERT OR UPDATE OF timesheet_id, bpay_work_key_v1, bpay_work_revision_v1, bpay_clock_family_id_v1 ON public.timesheet_payment_overrides FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_override_changed_v1();

-- public.timesheet_summary_pay_state_cache.bpay_clock_cache_v1  (piece A1_EXTRACT; tested name bpay_clock_cache_probe)
DROP TRIGGER IF EXISTS bpay_clock_cache_v1 ON public.timesheet_summary_pay_state_cache;
CREATE TRIGGER bpay_clock_cache_v1 AFTER INSERT OR DELETE OR UPDATE OF timesheet_id, advance_authorisation_consumed_at_utc ON public.timesheet_summary_pay_state_cache FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_changed_v1();

-- public.timesheets.bpay_clock_timesheet_v1  (piece A1_EXTRACT; tested name bpay_clock_timesheet_probe)
DROP TRIGGER IF EXISTS bpay_clock_timesheet_v1 ON public.timesheets;
CREATE TRIGGER bpay_clock_timesheet_v1 AFTER INSERT OR UPDATE OF booking_id, authorised_at_server, revoked_at ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_changed_v1();

-- public.timesheets.bpay_expense_classification_ts_after_v1  (piece A1_EXTRACT; tested name bpay_expense_classification_ts_after_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_ts_after_v1 ON public.timesheets;
CREATE TRIGGER bpay_expense_classification_ts_after_v1 AFTER INSERT OR UPDATE OF booking_id, contract_id, week_ending_date, sheet_scope, line_type, is_adjustment, settings_authority_json, settings_authority_version, settings_authority_resolved_at ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_ts_v1();

-- public.timesheets.bpay_expense_classification_ts_before_v1  (piece A1_EXTRACT; tested name bpay_expense_classification_ts_before_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_ts_before_v1 ON public.timesheets;
CREATE TRIGGER bpay_expense_classification_ts_before_v1 BEFORE INSERT OR UPDATE OF booking_id, contract_id, week_ending_date, sheet_scope, line_type, is_adjustment, settings_authority_json, settings_authority_version, settings_authority_resolved_at ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_ts_v1();

-- public.timesheets.bpay_source_timesheet_family_gate_v1  (piece A1_EXTRACT; tested name bpay_source_timesheet_family_gate_probe)
DROP TRIGGER IF EXISTS bpay_source_timesheet_family_gate_v1 ON public.timesheets;
CREATE TRIGGER bpay_source_timesheet_family_gate_v1 BEFORE INSERT OR DELETE OR UPDATE OF booking_id, is_current, version ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_source_timesheet_family_gate_v1();

-- public.timesheets.bpay_timesheet_work_revision_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_timesheet_work_revision_v1 ON public.timesheets;
CREATE TRIGGER bpay_timesheet_work_revision_v1 BEFORE INSERT OR UPDATE OF booking_id, bpay_work_revision_v1 ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_timesheet_work_revision_v1();

-- public.timesheets_financials.bpay_clock_financial_v1  (piece A1_EXTRACT; tested name bpay_clock_financial_probe)
DROP TRIGGER IF EXISTS bpay_clock_financial_v1 ON public.timesheets_financials;
CREATE TRIGGER bpay_clock_financial_v1 AFTER INSERT OR DELETE OR UPDATE OF timesheet_id, authorised_at_utc ON public.timesheets_financials FOR EACH ROW EXECUTE FUNCTION private.bpay_clock_changed_v1();

-- public.ts_pay_adjustments.bpay_work_reference_v1  (piece A1_EXTRACT)
DROP TRIGGER IF EXISTS bpay_work_reference_v1 ON public.ts_pay_adjustments;
CREATE TRIGGER bpay_work_reference_v1 BEFORE INSERT OR UPDATE OF timesheet_id, bpay_work_key_v1, bpay_work_revision_v1 ON public.ts_pay_adjustments FOR EACH ROW EXECUTE FUNCTION private.bpay_ts_pay_adjustments_work_reference_v1();

-- public.weekly_exceptional_pay_target_families.bpay_protected_root_reference_v1  (piece A1_EXTRACT; tested name bpay_protected_root_reference_probe)
DROP TRIGGER IF EXISTS bpay_protected_root_reference_v1 ON public.weekly_exceptional_pay_target_families;
CREATE TRIGGER bpay_protected_root_reference_v1 BEFORE INSERT OR UPDATE OF root_timesheet_id, bpay_root_work_revision_v1 ON public.weekly_exceptional_pay_target_families FOR EACH ROW EXECUTE FUNCTION private.bpay_protected_root_reference_v1();

-- public.weekly_exceptional_pay_target_families.bpay_source_protected_family_gate_v1  (piece A1_EXTRACT; tested name bpay_source_protected_family_gate_probe)
DROP TRIGGER IF EXISTS bpay_source_protected_family_gate_v1 ON public.weekly_exceptional_pay_target_families;
CREATE TRIGGER bpay_source_protected_family_gate_v1 BEFORE INSERT OR DELETE OR UPDATE OF root_family_booking_id, root_timesheet_id ON public.weekly_exceptional_pay_target_families FOR EACH ROW EXECUTE FUNCTION private.bpay_source_protected_family_gate_v1();

-- public.weekly_exceptional_payment_approvals.bpay_evidence_reference_v1  (piece A1_EXTRACT; tested name bpay_evidence_reference_probe)
DROP TRIGGER IF EXISTS bpay_evidence_reference_v1 ON public.weekly_exceptional_payment_approvals;
CREATE TRIGGER bpay_evidence_reference_v1 AFTER INSERT OR DELETE OR UPDATE ON public.weekly_exceptional_payment_approvals FOR EACH ROW EXECUTE FUNCTION private.bpay_protected_reference_capture_v1();

-- public.weekly_source_root_authorisations.bpay_authorisation_work_reference_v1  (piece A1_EXTRACT; tested name bpay_authorisation_work_reference_probe)
DROP TRIGGER IF EXISTS bpay_authorisation_work_reference_v1 ON public.weekly_source_root_authorisations;
CREATE TRIGGER bpay_authorisation_work_reference_v1 BEFORE INSERT ON public.weekly_source_root_authorisations FOR EACH ROW EXECUTE FUNCTION private.bpay_authorisation_work_reference_v1();

-- public.weekly_source_root_authorisations.bpay_source_auth_family_gate_v1  (piece A1_EXTRACT; tested name bpay_source_auth_family_gate_probe)
DROP TRIGGER IF EXISTS bpay_source_auth_family_gate_v1 ON public.weekly_source_root_authorisations;
CREATE TRIGGER bpay_source_auth_family_gate_v1 BEFORE INSERT OR DELETE OR UPDATE ON public.weekly_source_root_authorisations FOR EACH ROW EXECUTE FUNCTION private.bpay_source_auth_family_gate_v1();

-- public.weekly_source_row_timesheet_lineages.bpay_expense_classification_lineage_after_v1  (piece A1_EXTRACT; tested name bpay_expense_classification_lineage_after_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_lineage_after_v1 ON public.weekly_source_row_timesheet_lineages;
CREATE TRIGGER bpay_expense_classification_lineage_after_v1 AFTER INSERT ON public.weekly_source_row_timesheet_lineages FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_lineage_v1();

-- public.weekly_source_row_timesheet_lineages.bpay_expense_classification_lineage_before_v1  (piece A1_EXTRACT; tested name bpay_expense_classification_lineage_before_probe)
DROP TRIGGER IF EXISTS bpay_expense_classification_lineage_before_v1 ON public.weekly_source_row_timesheet_lineages;
CREATE TRIGGER bpay_expense_classification_lineage_before_v1 BEFORE INSERT ON public.weekly_source_row_timesheet_lineages FOR EACH ROW EXECUTE FUNCTION private.bpay_expense_classification_lineage_v1();

-- public.weekly_source_row_timesheet_lineages.bpay_lineage_work_binding_v1  (piece A1_EXTRACT; tested name bpay_lineage_work_binding_probe)
DROP TRIGGER IF EXISTS bpay_lineage_work_binding_v1 ON public.weekly_source_row_timesheet_lineages;
CREATE TRIGGER bpay_lineage_work_binding_v1 BEFORE INSERT ON public.weekly_source_row_timesheet_lineages FOR EACH ROW EXECUTE FUNCTION private.bpay_lineage_work_binding_v1();

-- public.weekly_source_row_timesheet_lineages.bpay_source_lineage_family_gate_v1  (piece A1_EXTRACT; tested name bpay_source_lineage_family_gate_probe)
DROP TRIGGER IF EXISTS bpay_source_lineage_family_gate_v1 ON public.weekly_source_row_timesheet_lineages;
CREATE TRIGGER bpay_source_lineage_family_gate_v1 BEFORE INSERT ON public.weekly_source_row_timesheet_lineages FOR EACH ROW EXECUTE FUNCTION private.bpay_source_lineage_family_gate_v1();

-- public.weekly_source_entitlement_heads.weekly_source_entitlement_head_ledger_mark  (piece A17_S1)
DROP TRIGGER IF EXISTS weekly_source_entitlement_head_ledger_mark ON public.weekly_source_entitlement_heads;
CREATE TRIGGER weekly_source_entitlement_head_ledger_mark
  AFTER INSERT OR UPDATE OF state ON public.weekly_source_entitlement_heads
  FOR EACH ROW EXECUTE FUNCTION private.weekly_source_entitlement_head_ledger_mark_v1();

commit;
