-- CANDIDATE release file generated by Worker BY (release-a35) from the tested Stage 2 winner piece A35
-- (h0/WINNER_REPLACEMENTS_A35_PLAN_CACHE.sql, sha256 e3dd09b20f0e1f5e12c9f1642080f43d96dffd1b41c18dd6cba0e8e43c931e72).
-- NOT committed, NOT installed anywhere. Builder: h8/release_a35/tools/a35_build_release_file.py.
-- Repeatable CloudTMS function authority: banking_pay_stage2_session_plan_cache_mode_v1
-- A35 (Worker BW "a35-plans"): planner-only fix for the PL/pgSQL call-6 generic-plan switch on two routines
-- that guard on parameter values -- public._pay_batch_item_economic_components(uuid,uuid[]) (A7's batch/by-id
-- item reader) and public.pay_timesheet_summary_pay_state_refresh_trigger() (the Timesheet pay-cache statement
-- trigger) -- each gets SET plan_cache_mode = force_custom_plan; the item reader also gets SET jit = off
-- (a forced custom plan of that reader is costed above the JIT threshold under the session default).
-- No body, owner, ACL, search_path or volatility change; no new routine. Policy X: planner settings only,
-- every measured result is identical with and without A35; no payment, provider, settlement, remittance,
-- email or webhook function is touched.
-- Supersedes, by engine order (sqlDateKey), no file: the two routines' own configuration is only extended,
-- so their last definers (26092026_0201 for the item reader; 04082026_1219 for the pay-cache trigger) are
-- unaffected and stay the definition source; this file only appends proconfig on top.
-- Sorts after 26092026_0207_banking_pay_stage2_recovery_headroom_revalidation_v1 (A33) and
-- 26092026_0207_banking_pay_stage2_recovery_order_floor_v1 (A34) -- 'session' > 'recovery' -- and before
-- 0208 and the grants closure 26092026_0209. Neither A33's nor A34's 0207 file defines either A35 routine;
-- this file is placed after both only so it provably sorts after every actual definer of the two routines,
-- which are strictly earlier (0201, 0203-era not applicable here, and the pre-Stage-2 owner files below).
-- The winner text below is carried verbatim (its own header, BEGIN/COMMIT and postcondition self-check).

\set ON_ERROR_STOP on

-- H0 A35 (Worker BW "a35-plans", 27 Sep 2026): routine-level plan_cache_mode = force_custom_plan (plus jit = off on the
-- item reader), as A6 did for jit.
-- Why: after five executions in one session PostgreSQL may replace a PL/pgSQL statement's fresh ("custom") plan by one
-- cached generic plan that does not know the parameter values (array sizes, which guarded branch is live).
--   * public._pay_batch_item_economic_components (A7's guarded by-id / by-batch sources): BS measured a generic-plan page
--     at ~4 s (2.9 M join-filter lookups) against 0.33 s custom on s3_work; BW reproduced a 2.2x slowdown from call 6 on
--     claude_w_draft (2,666-item batch 0.70 s -> 1.52 s; a freshness check 0.6 s -> 2.1 s; workers/a35/A35_REPORT.md).
--   * public.pay_timesheet_summary_pay_state_refresh_trigger (the Timesheet pay-cache statement trigger): WP5 measured
--     > 30 s per 25-100-item delete step on the generic plan against a worst 1.84 s custom. The setting is in force for the
--     whole trigger chain (pay_timesheet_summary_pay_state_refresh and the scope invalidation it calls).
--   * jit = off on public._pay_batch_item_economic_components as well (A6's setting, for the same reason): with the session
--     default jit=on, a forced custom plan of this reader is costed above the JIT optimise/inline thresholds on every call
--     (measured 2.8 s per 2,666-item batch; 0.7 s with jit off). Its A6 callers already run with jit=off; its direct
--     callers (freshness chunk, stale hint, export rows, Workbench pages) did not.
-- Planner setting only: no body, owner, ACL, search_path, volatility or result change (differential in the report).
-- LANGUAGE sql readers are not listed: PostgreSQL 17 plans their statements without parameter values on every call, so
-- they have no call-6 switch and plan_cache_mode does not apply to them.
-- Precedent already installed: private.pay_workbench_modal_eligible_rows_v2 carries SET plan_cache_mode = force_custom_plan.
-- Release form: put "SET plan_cache_mode TO 'force_custom_plan'" (and, for the item reader, "SET jit TO 'off'") in each
-- routine's repeatable definition (routine config enters the contract), exactly like A6's jit setting.
BEGIN;
ALTER FUNCTION public._pay_batch_item_economic_components(uuid, uuid[]) SET plan_cache_mode = force_custom_plan;
ALTER FUNCTION public._pay_batch_item_economic_components(uuid, uuid[]) SET jit = off;
ALTER FUNCTION public.pay_timesheet_summary_pay_state_refresh_trigger() SET plan_cache_mode = force_custom_plan;
DO $a35post$
DECLARE r record; n int := 0;
BEGIN
  FOR r IN SELECT p.oid::regprocedure AS sig, p.proconfig FROM pg_catalog.pg_proc p
           WHERE p.oid IN ('public._pay_batch_item_economic_components(uuid, uuid[])'::regprocedure,
                           'public.pay_timesheet_summary_pay_state_refresh_trigger()'::regprocedure) LOOP
    IF NOT ('plan_cache_mode=force_custom_plan' = ANY (r.proconfig)) THEN
      RAISE EXCEPTION 'A35_POSTCONDITION_FAILED: % config %', r.sig, r.proconfig;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM unnest(r.proconfig) c WHERE c LIKE 'search_path=%') THEN
      RAISE EXCEPTION 'A35_POSTCONDITION_FAILED: % lost search_path (%)', r.sig, r.proconfig;
    END IF;
    IF r.sig = 'public._pay_batch_item_economic_components(uuid, uuid[])'::regprocedure
       AND NOT ('jit=off' = ANY (r.proconfig)) THEN
      RAISE EXCEPTION 'A35_POSTCONDITION_FAILED: % config % (jit)', r.sig, r.proconfig;
    END IF;
    n := n + 1;
  END LOOP;
  IF n <> 2 THEN RAISE EXCEPTION 'A35_POSTCONDITION_FAILED: % of 2 routines found', n; END IF;
END
$a35post$;
COMMIT;
