-- Generated by scripts/generate-banking-pay-source-progress-facts.mjs.
-- Source: supabase/repeatable/07082026_2155_pay_workbench_session_recompute_progress_counters.sql
-- Complete source-scope facts, not the legacy owner's bounded diagnostic sample.
-- No new progress, payment, task, selection or job authority is introduced.
\set ON_ERROR_STOP on
begin;

CREATE OR REPLACE FUNCTION private.pay_workbench_modal_source_progress_facts_v2(
  p_session_id uuid, p_session_version bigint
) RETURNS TABLE (
  scope_id uuid, candidate_id uuid, scope_ordinal bigint, scope_status text,
  seeded boolean, dirty boolean, has_error boolean, publication_required boolean,
  publication_current boolean, source_ready boolean, source_failed boolean,
  recovery_required boolean, recovery_scheduled boolean, source_state text,
  pending_job_id uuid, owner_status text, owner_valid boolean,
  successor_job_id uuid, successor_job_status text, owner_failure_reason text
)
LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path TO ''
AS $function$
DECLARE
  v_session_row public.banking_pay_workbench_sessions%ROWTYPE;
  v_source_publication_identity_enforced boolean := false;
BEGIN
  SELECT s.* INTO v_session_row FROM public.banking_pay_workbench_sessions s WHERE s.id=p_session_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'WORKBENCH_SESSION_NOT_FOUND' USING ERRCODE='P0001'; END IF;
  IF p_session_version IS NULL OR p_session_version IS DISTINCT FROM v_session_row.version THEN
    RAISE EXCEPTION 'BANKING_PAY_V2_STALE_REVISION' USING ERRCODE='P0001';
  END IF;
  SELECT COALESCE(setting.banking_pay_source_publication_identity_enforce_v1_enabled,false)
  INTO v_source_publication_identity_enforced
  FROM public.settings_defaults AS setting
  ORDER BY setting.id
  LIMIT 1;
  RETURN QUERY
  WITH classified_scope AS (
    SELECT
      scope_row.id,
      UPPER(BTRIM(COALESCE(scope_row.status, ''))) AS status_key,
      COALESCE(scope_row.seeded, false) AS seeded,
      COALESCE(scope_row.dirty, false) AS dirty,
      NOT (
        scope_row.error_json IS NULL
        OR scope_row.error_json = '{}'::jsonb
        OR scope_row.error_json = 'null'::jsonb
      ) AS has_error,
      scope_row.certified_preview_publication_required IS TRUE AS publication_required,
      (
        scope_row.certified_preview_publication_required IS NOT TRUE
        OR (
          scope_row.certified_preview_publication_parity_ok IS TRUE
          AND scope_row.certified_preview_publication_session_version = v_session_row.version
          AND scope_row.certified_preview_publication_source_change_seq = candidate_state.source_change_seq
          AND scope_row.certified_preview_publication_source_build_run_id IS NOT NULL
          AND scope_row.certified_preview_publication_attested_at_utc IS NOT NULL
          AND scope_row.certified_preview_publication_attestation_json->>'parity_complete'='true'
          AND (
            (
              scope_row.certified_preview_publication_attestation_json->>'attestation_version'='CERTIFIED_SOURCE_PREVIEW_PUBLICATION_V1'
              AND scope_row.certified_preview_publication_attestation_json->>'authority_kind'='BOUNDED_FULL_SOURCE_BUILD'
            )
            OR (
              scope_row.certified_preview_publication_attestation_json->>'attestation_version'='CERTIFIED_SOURCE_PREVIEW_PUBLICATION_V2'
              AND scope_row.certified_preview_publication_attestation_json->>'contract_version'='2'
              AND scope_row.certified_preview_publication_attestation_json->>'authority_kind' IN ('CERTIFIED_CLONE','TARGETED_DELTA')
              AND scope_row.certified_preview_publication_attestation_json->>'final_state' IN ('READY','SOURCE_EMPTY')
            )
            OR (
              scope_row.certified_preview_publication_attestation_json->>'attestation_version'='CERTIFIED_SOURCE_PREVIEW_PUBLICATION_V3'
              AND scope_row.certified_preview_publication_attestation_json->>'contract_version'='3'
              AND scope_row.certified_preview_publication_attestation_json->>'semantic_contract_version'='READY_TO_PAY_SEMANTIC_V2'
              AND scope_row.certified_preview_publication_attestation_json->>'authority_kind' IN (
                'BOUNDED_FULL_SOURCE_BUILD','CERTIFIED_CLONE','TARGETED_DELTA','CERTIFIED_CANCELLATION_REVERSION'
              )
              AND scope_row.certified_preview_publication_attestation_json->>'final_state' IN ('READY','SOURCE_EMPTY')
              AND scope_row.certified_preview_publication_attestation_json->>'semantic_ready'='true'
              AND COALESCE((scope_row.certified_preview_publication_attestation_json->>'invalid_selectable_row_count')::integer,-1)=0
              AND (scope_row.certified_preview_publication_attestation_json->>'candidate_ready_amount')::numeric>=0
              AND NULLIF(BTRIM(COALESCE(scope_row.certified_preview_publication_attestation_json->>'semantic_proof_digest','')),'') IS NOT NULL
              AND (
                NOT v_source_publication_identity_enforced
                OR (
                  scope_row.certified_preview_publication_source_publication_id IS NOT NULL
                  AND scope_row.certified_preview_publication_attestation_json->>'source_publication_id'
                        =scope_row.certified_preview_publication_source_publication_id::text
                )
              )
            )
          )
        )
      ) AS publication_current
    FROM public.banking_pay_workbench_session_scope AS scope_row
    LEFT JOIN public.banking_pay_workbench_session_candidate_state AS candidate_state
      ON candidate_state.session_id = scope_row.session_id
     AND candidate_state.candidate_id = scope_row.candidate_id
    WHERE scope_row.session_id = p_session_id
  ),
  source_pending AS (
    SELECT
      scope_row.candidate_id,
      scope_row.scope_ordinal,
      scope_row.pending_job_id,
      owner_job.status AS owner_status,
      owner_job.attempt_count,
      owner_job.max_attempts,
      successor_lookup.successor_job_id,
      successor_lookup.successor_job_status,
      (
        owner_job.id IS NOT NULL
        AND owner_job.session_id = scope_row.session_id
        AND owner_job.candidate_id = scope_row.candidate_id
        AND UPPER(BTRIM(COALESCE(owner_job.status, ''))) IN ('QUEUED', 'RUNNING')
        AND UPPER(BTRIM(COALESCE(owner_job.job_type, ''))) IN (
          'WORKBENCH_CANDIDATE_SOURCE_BUILD',
          'WORKBENCH_CANDIDATE_SOURCE_BUILD_CHUNK',
          'WORKBENCH_CANDIDATE_SOURCE_BUILD_PAGE',
          'CANDIDATE_SOURCE_BUILD',
          'CANDIDATE_SOURCE_BUILD_CHUNK',
          'SOURCE_BUILD',
          'SOURCE_BUILD_PAGE'
        )
        AND CASE
              WHEN COALESCE(owner_job.payload_json->>'session_version', '') ~ '^[0-9]{1,18}$'
                THEN (owner_job.payload_json->>'session_version')::bigint
              ELSE NULL::bigint
            END = v_session_row.version
        AND CASE
              WHEN COALESCE(owner_job.payload_json->>'source_change_seq', '') ~ '^[0-9]{1,18}$'
                THEN (owner_job.payload_json->>'source_change_seq')::bigint
              ELSE NULL::bigint
            END >= COALESCE(change_counter.seq, 0)
        AND COALESCE(owner_job.payload_json->>'source_build_run_id', '') ~*
            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      ) AS owner_valid,
      successor_lookup.successor_job_id IS NOT NULL AS successor_valid
    FROM public.banking_pay_workbench_session_scope AS scope_row
    LEFT JOIN public.banking_pay_workbench_jobs AS owner_job
      ON owner_job.id = scope_row.pending_job_id
    LEFT JOIN public.app_change_counters AS change_counter
      ON change_counter.entity_key = 'pay_candidate:' || scope_row.candidate_id::text
    LEFT JOIN LATERAL (
      SELECT
        successor_job.id AS successor_job_id,
        UPPER(BTRIM(COALESCE(successor_job.status, ''))) AS successor_job_status
      FROM public.banking_pay_workbench_jobs AS successor_job
      WHERE successor_job.id IS DISTINCT FROM scope_row.pending_job_id
        AND successor_job.session_id = scope_row.session_id
        AND successor_job.candidate_id = scope_row.candidate_id
        AND UPPER(BTRIM(COALESCE(successor_job.status, ''))) IN ('QUEUED', 'RUNNING')
        AND UPPER(BTRIM(COALESCE(successor_job.job_type, ''))) IN (
          'WORKBENCH_CANDIDATE_SOURCE_BUILD',
          'WORKBENCH_CANDIDATE_SOURCE_BUILD_CHUNK',
          'WORKBENCH_CANDIDATE_SOURCE_BUILD_PAGE',
          'CANDIDATE_SOURCE_BUILD',
          'CANDIDATE_SOURCE_BUILD_CHUNK',
          'SOURCE_BUILD',
          'SOURCE_BUILD_PAGE'
        )
        AND CASE
              WHEN COALESCE(successor_job.payload_json->>'session_version', '') ~ '^[0-9]{1,18}$'
                THEN (successor_job.payload_json->>'session_version')::bigint
              ELSE NULL::bigint
            END = v_session_row.version
        AND CASE
              WHEN COALESCE(successor_job.payload_json->>'source_change_seq', '') ~ '^[0-9]{1,18}$'
                THEN (successor_job.payload_json->>'source_change_seq')::bigint
              ELSE NULL::bigint
            END >= COALESCE(change_counter.seq, 0)
        AND COALESCE(successor_job.payload_json->>'source_build_run_id', '') ~*
            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      ORDER BY
        CASE WHEN UPPER(BTRIM(COALESCE(successor_job.status, ''))) = 'RUNNING' THEN 0 ELSE 1 END,
        CASE
          WHEN COALESCE(successor_job.payload_json->>'source_change_seq', '') ~ '^[0-9]{1,18}$'
            THEN (successor_job.payload_json->>'source_change_seq')::bigint
          ELSE NULL::bigint
        END DESC,
        successor_job.created_at_utc ASC,
        successor_job.id ASC
      LIMIT 1
    ) AS successor_lookup ON TRUE
    WHERE scope_row.session_id = p_session_id
      AND UPPER(BTRIM(COALESCE(scope_row.status, ''))) = 'SOURCE_BUILD_PENDING'
  ), ownership_failure AS (
    SELECT
      source_pending.*,
      CASE
        WHEN source_pending.pending_job_id IS NULL THEN 'PENDING_JOB_ID_MISSING'
        WHEN source_pending.owner_status IS NULL THEN 'PENDING_JOB_ROW_MISSING'
        WHEN UPPER(BTRIM(COALESCE(source_pending.owner_status, ''))) NOT IN ('QUEUED', 'RUNNING') THEN 'PENDING_JOB_TERMINAL'
        ELSE 'PENDING_JOB_CONTEXT_INVALID'
      END AS owner_failure_reason
    FROM source_pending
    WHERE source_pending.owner_valid IS NOT TRUE
  ),
  facts AS (
    SELECT c.*,
      (c.dirty IS NOT TRUE AND c.has_error IS NOT TRUE AND c.publication_current IS TRUE
        AND c.status_key IN ('READY','MATERIALISED','MATERIALIZED','SOURCE_EMPTY')) AS ready,
      (c.has_error IS TRUE OR c.status_key IN ('FAILED','ERROR','LINE_WORK_ERROR','LINE_WORK_PROCESS_ERROR','SOURCE_BUILD_ERROR')) AS failed,
      (f.candidate_id IS NOT NULL AND f.successor_valid IS NOT TRUE) AS recovery_required,
      (f.candidate_id IS NOT NULL AND f.successor_valid IS TRUE) AS recovery_scheduled,
      s.candidate_id, s.scope_ordinal, s.pending_job_id, p.owner_status, p.owner_valid,
      p.successor_job_id, p.successor_job_status, f.owner_failure_reason
    FROM classified_scope c
    JOIN public.banking_pay_workbench_session_scope s ON s.id=c.id
    LEFT JOIN source_pending p ON p.candidate_id=s.candidate_id
    LEFT JOIN ownership_failure f ON f.candidate_id=s.candidate_id
  )
  SELECT f.id, f.candidate_id, f.scope_ordinal::bigint, f.status_key,
    f.seeded, f.dirty, f.has_error, f.publication_required, f.publication_current,
    f.ready, f.failed, f.recovery_required, f.recovery_scheduled,
    CASE WHEN f.failed OR f.recovery_required THEN 'REFRESH_REQUIRED'
         WHEN f.ready THEN 'CURRENT' ELSE 'UPDATING' END,
    f.pending_job_id, f.owner_status, f.owner_valid, f.successor_job_id,
    f.successor_job_status, f.owner_failure_reason
  FROM facts f;
END;
$function$;
ALTER FUNCTION private.pay_workbench_modal_source_progress_facts_v2(uuid,bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION private.pay_workbench_modal_source_progress_facts_v2(uuid,bigint) FROM PUBLIC, anon, authenticated, service_role;
commit;
