/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: cdeafc518d0fe9f5dcbbbfb40e12c8e2)
interface __BaseEnv_Env {
	MIGET_POSTGREST_ORIGIN: "https://mytms-control-plane-postgrest-mwzkq.eu-east-1.migetapp.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MIGET_POSTGREST_ORIGIN">> {}
}
