-- CANDIDATE one-time migration generated by Worker AF (H8) from the tested Stage 2 combined candidate.
-- NOT committed, NOT installed anywhere. Source pieces and hashes: h8/RELEASE_FORM_RESULT.json.
-- Probe/prototype identifiers renamed to production names per h8/tools/rename_map.json.
-- Policy X: no economic-key derivation, freshness or post-Draft behaviour change beyond the tested winners.
-- One-time CloudTMS schema migration: banking_pay_stage2_work_reference_schema
-- Tables, columns, constraints and indexes for the Stage 2 candidate (tested extract A1 + A4 + A14).
-- [Worker AI amendment] Formerly CLEAN-START ONLY: the tested candidate had no backfill for existing Timesheet/payment rows (COMBINED_CANDIDATE G04,
-- STATUS H2 G-A4). The guard below therefore refuses to run on a database that already holds rows the new
-- work-reference / clock / protected-reference structures would need to describe. It never modifies data.
-- [Worker AU amendment REL-GENCOL] timesheets.bpay_work_key_v1 is an ORDINARY column maintained by the BEFORE
-- INSERT OR UPDATE trigger zz_bpay_timesheet_work_key_v1 (ENABLE ALWAYS, fires last) with exactly the former
-- generation expression, and guarded by CHECK bpay_timesheet_work_key_expression_v1 (NOT VALID here; validated by
-- the backfill). A STORED GENERATED column refused the product's whole-row Timesheet copies
-- (INSERT INTO public.timesheets SELECT (row).* in private._timesheet_route_version_legacy_v1 and
-- public.contract_week_manual_upsert_atomic: "cannot insert a non-DEFAULT value") and was NULL inside every BEFORE
-- trigger, which made timesheet_archive_row_guard_v1's to_jsonb(OLD)/to_jsonb(NEW) comparison refuse every Archive
-- transition (ARCHIVE_TRANSITION_METADATA_ONLY). Existing rows are still filled by the same table rewrite
-- (ADD COLUMN ... GENERATED ... STORED), then DROP EXPRESSION keeps those stored values: no trigger fires, no value
-- changes, and the lock is the one M1 already took.

\set ON_ERROR_STOP on

begin;

-- [Worker AI amendment] The clean-start guard is removed: existing rows are filled by the Stage 2 backfill
-- (h8/release_candidate/supabase/migrations/26092026_0199_banking_pay_stage2_backfill.sql, to be re-stamped after this
-- file), which refuses underivable rows itself before writing anything.

-- Tables (moved into private; protected-reference tables formerly in the prototype evidence schema)
CREATE TABLE private.bpay_protected_reference_events_v1 (
  family_id uuid NOT NULL,
  ordinal bigint NOT NULL,
  approval_id uuid NOT NULL,
  approval_hash bytea NOT NULL,
  active boolean NOT NULL,
  previous_digest bytea NOT NULL,
  digest bytea NOT NULL
);
CREATE TABLE private.bpay_protected_reference_heads_v1 (
  family_id uuid NOT NULL,
  ordinal bigint NOT NULL,
  digest bytea NOT NULL
);
CREATE TABLE private.bpay_clock_families_v1 (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  booking_id text NOT NULL
);
CREATE TABLE private.bpay_clock_rows_v1 (
  timesheet_id uuid NOT NULL,
  family_id uuid NOT NULL,
  authorisation_at timestamp with time zone,
  consumed_at timestamp with time zone
);
alter table private.bpay_protected_reference_events_v1 owner to postgres;
revoke all on private.bpay_protected_reference_events_v1 from public,anon,authenticated,service_role;
alter table private.bpay_protected_reference_events_v1 enable row level security;
alter table private.bpay_protected_reference_events_v1 force row level security;
create policy bpay_protected_reference_events_v1_owner on private.bpay_protected_reference_events_v1
  to current_user using(true) with check(true);
alter table private.bpay_protected_reference_heads_v1 owner to postgres;
revoke all on private.bpay_protected_reference_heads_v1 from public,anon,authenticated,service_role;
alter table private.bpay_protected_reference_heads_v1 enable row level security;
alter table private.bpay_protected_reference_heads_v1 force row level security;
create policy bpay_protected_reference_heads_v1_owner on private.bpay_protected_reference_heads_v1
  to current_user using(true) with check(true);
alter table private.bpay_clock_families_v1 owner to postgres;
revoke all on private.bpay_clock_families_v1 from public,anon,authenticated,service_role;
alter table private.bpay_clock_families_v1 enable row level security;
alter table private.bpay_clock_families_v1 force row level security;
create policy bpay_clock_families_v1_owner on private.bpay_clock_families_v1
  to current_user using(true) with check(true);
alter table private.bpay_clock_rows_v1 owner to postgres;
revoke all on private.bpay_clock_rows_v1 from public,anon,authenticated,service_role;
alter table private.bpay_clock_rows_v1 enable row level security;
alter table private.bpay_clock_rows_v1 force row level security;
create policy bpay_clock_rows_v1_owner on private.bpay_clock_rows_v1
  to current_user using(true) with check(true);

-- Columns
ALTER TABLE public.pay_batch_items ADD COLUMN bpay_direct_source_timesheet_id_v1 uuid;
ALTER TABLE public.pay_batch_items ADD COLUMN bpay_direct_work_key_v1 text;
ALTER TABLE public.pay_batch_items ADD COLUMN bpay_direct_work_revision_v1 bigint;
ALTER TABLE public.pay_finance_case_components ADD COLUMN bpay_work_key_v1 text;
ALTER TABLE public.pay_finance_case_components ADD COLUMN bpay_work_revision_v1 bigint;
ALTER TABLE public.timesheet_pay_state ADD COLUMN bpay_work_key_v1 text;
ALTER TABLE public.timesheet_pay_state ADD COLUMN bpay_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.timesheet_payment_overrides ADD COLUMN bpay_work_key_v1 text;
ALTER TABLE public.timesheet_payment_overrides ADD COLUMN bpay_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.timesheet_payment_overrides ADD COLUMN bpay_clock_family_id_v1 uuid;
ALTER TABLE public.timesheets ADD COLUMN bpay_work_key_v1 text GENERATED ALWAYS AS (
CASE
    WHEN ((booking_id IS NOT NULL) AND (btrim(booking_id) <> ''::text)) THEN booking_id
    ELSE NULL::text
END) STORED;
-- [Worker AU amendment REL-GENCOL] keep the values the rewrite above stored; from here on the trigger below maintains them.
ALTER TABLE public.timesheets ALTER COLUMN bpay_work_key_v1 DROP EXPRESSION;
ALTER TABLE public.timesheets ADD COLUMN bpay_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.ts_pay_adjustments ADD COLUMN bpay_work_key_v1 text;
ALTER TABLE public.ts_pay_adjustments ADD COLUMN bpay_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.weekly_exceptional_pay_target_families ADD COLUMN bpay_root_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.weekly_source_root_authorisations ADD COLUMN bpay_evidence_codec_v1 smallint DEFAULT 1 NOT NULL;
ALTER TABLE public.weekly_source_root_authorisations ADD COLUMN bpay_evidence_reference_v1 jsonb;
ALTER TABLE public.weekly_source_root_authorisations ADD COLUMN bpay_root_work_revision_v1 bigint DEFAULT 0 NOT NULL;
ALTER TABLE public.weekly_source_row_timesheet_lineages ADD COLUMN bpay_lineage_work_revision_v1 bigint DEFAULT 0 NOT NULL;

-- Constraints (primary/unique, check, foreign key)
-- [Worker AI amendment] Every new CHECK/FOREIGN KEY on a pre-existing public table is added NOT VALID (brief lock, no
-- scan; still enforced for every new write) and validated by the backfill under SHARE UPDATE EXCLUSIVE. The
-- pay_finance_case_components pair (bpay_finance_component_work_presence_v1 / _reference_v1) is not added here: old
-- code inserting a linked component between this migration and R4 would violate it. The backfill adds it (same text)
-- in COMPLETE mode, after R4 installed the maintaining trigger.
ALTER TABLE private.bpay_protected_reference_events_v1 ADD CONSTRAINT bpay_protected_reference_events_v1_pkey PRIMARY KEY (family_id, ordinal);
ALTER TABLE private.bpay_protected_reference_heads_v1 ADD CONSTRAINT bpay_protected_reference_heads_v1_pkey PRIMARY KEY (family_id);
ALTER TABLE private.bpay_clock_families_v1 ADD CONSTRAINT bpay_clock_families_v1_pkey PRIMARY KEY (id);
ALTER TABLE private.bpay_clock_rows_v1 ADD CONSTRAINT bpay_clock_rows_v1_pkey PRIMARY KEY (timesheet_id);
ALTER TABLE private.bpay_clock_families_v1 ADD CONSTRAINT bpay_clock_families_v1_booking_id_key UNIQUE (booking_id);
ALTER TABLE public.timesheets ADD CONSTRAINT bpay_timesheet_work_identity_v1 UNIQUE (timesheet_id, bpay_work_revision_v1);
ALTER TABLE private.bpay_protected_reference_events_v1 ADD CONSTRAINT bpay_protected_reference_events_v1_approval_hash_check CHECK ((octet_length(approval_hash) = 32));
ALTER TABLE private.bpay_protected_reference_events_v1 ADD CONSTRAINT bpay_protected_reference_events_v1_digest_check CHECK (((octet_length(previous_digest) = 32) AND (octet_length(digest) = 32)));
ALTER TABLE private.bpay_protected_reference_events_v1 ADD CONSTRAINT bpay_protected_reference_events_v1_ordinal_check CHECK ((ordinal > 0));
ALTER TABLE private.bpay_protected_reference_heads_v1 ADD CONSTRAINT bpay_protected_reference_heads_v1_digest_check CHECK ((octet_length(digest) = 32));
ALTER TABLE private.bpay_protected_reference_heads_v1 ADD CONSTRAINT bpay_protected_reference_heads_v1_ordinal_check CHECK ((ordinal >= 0));
-- [Worker CA amendment ORPHAN-V5] A pay item may record a Timesheet reference (item timesheet_id, else the UUID-shaped
-- frozen basis timesheet_id) whose Timesheet row no longer exists (hosted TEST: 165 such items). Today's code maps
-- that item to the recorded UUID and nothing else. The item trigger therefore stores the recorded UUID with key and
-- revision NULL. This CHECK admits exactly that shape: a revision needs a reference, and a key needs a revision.
ALTER TABLE public.pay_batch_items ADD CONSTRAINT bpay_item_work_reference_presence_v1 CHECK ((((bpay_direct_work_revision_v1 IS NULL) OR (bpay_direct_source_timesheet_id_v1 IS NOT NULL)) AND ((bpay_direct_work_key_v1 IS NULL) OR (bpay_direct_work_revision_v1 IS NOT NULL)))) NOT VALID;
ALTER TABLE public.weekly_source_root_authorisations ADD CONSTRAINT bpay_evidence_shape_v1 CHECK ((((bpay_evidence_codec_v1 = 1) AND (bpay_evidence_reference_v1 IS NULL)) OR ((bpay_evidence_codec_v1 = 2) AND (bpay_evidence_reference_v1 IS NOT NULL) AND (protected_decision_hashes IS NULL)))) NOT VALID;
ALTER TABLE private.bpay_protected_reference_events_v1 ADD CONSTRAINT bpay_protected_reference_events_v1_family_id_fkey FOREIGN KEY (family_id) REFERENCES private.bpay_protected_reference_heads_v1(family_id);
ALTER TABLE private.bpay_clock_rows_v1 ADD CONSTRAINT bpay_clock_rows_v1_family_id_fkey FOREIGN KEY (family_id) REFERENCES private.bpay_clock_families_v1(id);
ALTER TABLE private.bpay_clock_rows_v1 ADD CONSTRAINT bpay_clock_rows_v1_timesheet_id_fkey FOREIGN KEY (timesheet_id) REFERENCES public.timesheets(timesheet_id) ON DELETE CASCADE;
-- [Worker CA amendment ORPHAN-V5] MATCH SIMPLE (an orphan has a reference but no revision, so it is not checked) and
-- ON DELETE SET NULL (revision only): deleting a Timesheet keeps the recorded reference and clears only the live
-- revision, and the item trigger then clears the key. Today a Timesheet whose only pay-item reference is the frozen
-- UUID can be deleted; MATCH FULL with NO ACTION refused that delete, which would have been a behaviour change.
ALTER TABLE public.pay_batch_items ADD CONSTRAINT bpay_item_work_reference_v1 FOREIGN KEY (bpay_direct_source_timesheet_id_v1, bpay_direct_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) ON DELETE SET NULL (bpay_direct_work_revision_v1) NOT VALID;
ALTER TABLE public.timesheet_pay_state ADD CONSTRAINT bpay_timesheet_pay_state_work_fk FOREIGN KEY (timesheet_id, bpay_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
ALTER TABLE public.timesheet_payment_overrides ADD CONSTRAINT bpay_timesheet_payment_overrides_work_fk FOREIGN KEY (timesheet_id, bpay_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
ALTER TABLE public.timesheet_payment_overrides ADD CONSTRAINT timesheet_payment_overrides_bpay_clock_family_id_v1_fkey FOREIGN KEY (bpay_clock_family_id_v1) REFERENCES private.bpay_clock_families_v1(id) NOT VALID;
ALTER TABLE public.ts_pay_adjustments ADD CONSTRAINT bpay_ts_pay_adjustments_work_fk FOREIGN KEY (timesheet_id, bpay_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
ALTER TABLE public.weekly_exceptional_pay_target_families ADD CONSTRAINT bpay_protected_root_work_v1 FOREIGN KEY (root_timesheet_id, bpay_root_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
ALTER TABLE public.weekly_source_root_authorisations ADD CONSTRAINT bpay_authorisation_work_reference_v1 FOREIGN KEY (root_timesheet_id, bpay_root_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
ALTER TABLE public.weekly_source_row_timesheet_lineages ADD CONSTRAINT bpay_lineage_work_revision_fk_v1 FOREIGN KEY (timesheet_id, bpay_lineage_work_revision_v1) REFERENCES public.timesheets(timesheet_id, bpay_work_revision_v1) NOT VALID;
-- [Worker AU amendment REL-GENCOL] the former generation expression, as a constraint (validated by the backfill).
ALTER TABLE public.timesheets ADD CONSTRAINT bpay_timesheet_work_key_expression_v1 CHECK ((bpay_work_key_v1 IS NOT DISTINCT FROM
CASE
    WHEN ((booking_id IS NOT NULL) AND (btrim(booking_id) <> ''::text)) THEN booking_id
    ELSE NULL::text
END)) NOT VALID;

-- [Worker AU amendment REL-GENCOL] Maintaining trigger for timesheets.bpay_work_key_v1. It is installed here, not in a
-- repeatable, because the column must be maintained from the moment this migration commits (the backfill and old code
-- write in between). Always recomputed from the final booking_id: a whole-row copy or an explicit value cannot leave a
-- different key. Named zz_ so it fires after every other BEFORE trigger (booking_id is final, and earlier BEFORE
-- triggers see OLD's value on UPDATE rather than a changed key); ENABLE ALWAYS so session_replication_role=replica does
-- not skip it (a generated column was not skipped either). SECURITY INVOKER, owner-only EXECUTE.
CREATE FUNCTION private.bpay_timesheet_work_key_v1()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog', 'public', 'private', 'pg_temp'
AS $function$
BEGIN
 NEW.bpay_work_key_v1:=CASE
   WHEN ((NEW.booking_id IS NOT NULL) AND (btrim(NEW.booking_id) <> ''::text)) THEN NEW.booking_id
   ELSE NULL::text
 END;
 RETURN NEW;
END;
$function$;
ALTER FUNCTION private.bpay_timesheet_work_key_v1() OWNER TO postgres;
REVOKE ALL ON FUNCTION private.bpay_timesheet_work_key_v1() FROM PUBLIC, anon, authenticated, service_role;
CREATE TRIGGER zz_bpay_timesheet_work_key_v1 BEFORE INSERT OR UPDATE ON public.timesheets FOR EACH ROW EXECUTE FUNCTION private.bpay_timesheet_work_key_v1();
ALTER TABLE public.timesheets ENABLE ALWAYS TRIGGER zz_bpay_timesheet_work_key_v1;

-- A14 precondition: the A14 partial indexes rely on the status CHECK and NOT NULL columns
DO $a14$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.banking_pay_workbench_jobs'::regclass
      AND conname = 'banking_pay_workbench_jobs_status_chk'
      AND convalidated
      AND pg_get_constraintdef(oid) = 'CHECK ((status = ANY (ARRAY[''QUEUED''::text, ''RUNNING''::text, ''SUCCEEDED''::text, ''FAILED''::text, ''DEAD''::text])))'
  ) OR EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.banking_pay_workbench_jobs'::regclass AND attname IN ('status', 'dedupe_key') AND NOT attnotnull
  ) THEN
    RAISE EXCEPTION 'A14_WB_READERS_PRECONDITION_FAILED: banking_pay_workbench_jobs status CHECK / NOT NULL changed';
  END IF;
END
$a14$;

-- Indexes (tested extract, A4 FK-support indexes, A14 Workbench reader indexes)
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_family_trim_v1 ON private.bpay_clock_families_v1 USING btree (btrim(booking_id));
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_rows_v1_family_id_authorisation_at_idx ON private.bpay_clock_rows_v1 USING btree (family_id, authorisation_at DESC NULLS LAST);
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_rows_v1_family_id_consumed_at_idx ON private.bpay_clock_rows_v1 USING btree (family_id, consumed_at DESC NULLS LAST);
-- piece A1_EXTRACT
CREATE INDEX bpay_auth_live_trim_v1 ON public.weekly_source_root_authorisations USING btree (btrim(family_booking_id)) WHERE (withdrawn_at_utc IS NULL);
-- piece A1_EXTRACT
CREATE UNIQUE INDEX bpay_authorisation_live_family_v1 ON public.weekly_source_root_authorisations USING btree (family_booking_id) WHERE (withdrawn_at_utc IS NULL);
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_financial_event_v1 ON public.timesheets_financials USING btree (timesheet_id, authorised_at_utc DESC NULLS LAST);
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_override_family_v1 ON public.timesheet_payment_overrides USING btree (bpay_clock_family_id_v1);
-- piece A1_EXTRACT
CREATE INDEX bpay_clock_override_latest_v1 ON public.timesheet_payment_overrides USING btree (bpay_clock_family_id_v1, created_at_utc DESC, id DESC) WHERE ((cleared_at_utc IS NULL) AND (upper(btrim(COALESCE(override_type, ''::text))) = 'ADVANCE_THIS_PAYMENT'::text));
-- piece A1_EXTRACT
CREATE INDEX bpay_finance_component_work_v1 ON public.pay_finance_case_components USING btree (bpay_work_key_v1) WHERE (bpay_work_key_v1 IS NOT NULL);
-- piece A1_EXTRACT
CREATE INDEX bpay_item_component_fallback_v1 ON public.pay_batch_items USING btree (finance_component_id, id) WHERE ((bpay_direct_source_timesheet_id_v1 IS NULL) AND (finance_component_id IS NOT NULL));
-- piece A1_EXTRACT
CREATE INDEX bpay_item_direct_work_v1 ON public.pay_batch_items USING btree (bpay_direct_work_key_v1) WHERE (bpay_direct_work_key_v1 IS NOT NULL);
-- piece A1_EXTRACT
CREATE INDEX bpay_lineage_physical_v1 ON public.weekly_source_row_timesheet_lineages USING btree (timesheet_id);
-- piece A1_EXTRACT
CREATE INDEX bpay_lineage_trim_family_v1 ON public.weekly_source_row_timesheet_lineages USING btree (btrim(family_booking_id));
-- piece A1_EXTRACT
CREATE INDEX bpay_source_active_claim_owner_v1 ON public.candidate_expense_components USING btree (owning_timesheet_id) WHERE (lifecycle_state <> ALL (ARRAY['MANAGER_REFUSED'::text, 'OFFICE_REJECTED'::text, 'WITHDRAWN'::text, 'CANCELLED'::text, 'SUPERSEDED'::text]));
-- piece A1_EXTRACT
CREATE INDEX bpay_timesheet_pay_state_work_idx ON public.timesheet_pay_state USING btree (bpay_work_key_v1);
-- piece A1_EXTRACT
CREATE INDEX bpay_timesheet_payment_overrides_work_idx ON public.timesheet_payment_overrides USING btree (bpay_work_key_v1) WHERE ((cleared_at_utc IS NULL) AND (upper(btrim(COALESCE(override_type, ''::text))) = 'ADVANCE_THIS_PAYMENT'::text));
-- piece A1_EXTRACT
CREATE INDEX bpay_ts_pay_adjustments_work_idx ON public.ts_pay_adjustments USING btree (bpay_work_key_v1);
-- piece A4
CREATE INDEX bpay_item_work_reference_fk_v1 ON public.pay_batch_items(bpay_direct_source_timesheet_id_v1,bpay_direct_work_revision_v1)
  WHERE bpay_direct_source_timesheet_id_v1 IS NOT NULL;
-- piece A4
CREATE INDEX bpay_timesheet_payment_overrides_work_fk_v1 ON public.timesheet_payment_overrides(timesheet_id,bpay_work_revision_v1);
-- piece A14
CREATE INDEX IF NOT EXISTS idx_bpay_wb_jobs_generated_live_v1
  ON public.banking_pay_workbench_jobs USING btree (scope_change_generation)
  WHERE scope_change_generation IS NOT NULL AND job_type IN ('WORKBENCH_CANDIDATE_DIRTY_APPLY', 'WORKBENCH_FINANCE_CASE_DIRTY_APPLY', 'CONTRACT_CLIENT_DIRTY_FANOUT') AND status IN ('QUEUED', 'RUNNING', 'FAILED', 'DEAD');
-- piece A14
CREATE INDEX IF NOT EXISTS idx_bpay_wb_jobs_generated_unscoped_done_v1
  ON public.banking_pay_workbench_jobs USING btree (scope_change_generation)
  WHERE scope_change_generation IS NOT NULL AND job_type IN ('WORKBENCH_CANDIDATE_DIRTY_APPLY', 'WORKBENCH_FINANCE_CASE_DIRTY_APPLY', 'CONTRACT_CLIENT_DIRTY_FANOUT') AND status = 'SUCCEEDED' AND (candidate_id IS NULL OR job_type = 'CONTRACT_CLIENT_DIRTY_FANOUT');
-- piece A14
CREATE INDEX IF NOT EXISTS idx_bpay_wb_jobs_generated_padded_key_v1
  ON public.banking_pay_workbench_jobs USING btree (md5(BTRIM(dedupe_key)))
  WHERE scope_change_generation IS NOT NULL AND job_type IN ('WORKBENCH_CANDIDATE_DIRTY_APPLY', 'WORKBENCH_FINANCE_CASE_DIRTY_APPLY', 'CONTRACT_CLIENT_DIRTY_FANOUT') AND dedupe_key <> BTRIM(dedupe_key);

commit;
